# Generated by Django 5.0.6 on 2024-05-18 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0006_profile_following_alter_profile_followers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='media\\images\\default.png', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, default=(), related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, default=(), related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_picture', models.ImageField(default='images/images.png', upload_to='images/posts')),
                ('post_description', models.CharField(max_length=60)),
                ('hastags', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, default=(), related_name='image_liked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_description', models.CharField(max_length=60)),
                ('hastags', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, default=(), related_name='text_liked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
