# Generated by Django 5.0.6 on 2024-05-18 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0008_alter_imagepost_likes_alter_profile_followers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='hastags',
            new_name='hastag',
        ),
        migrations.RenameField(
            model_name='textpost',
            old_name='hastags',
            new_name='hastag',
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='likes',
            field=models.ManyToManyField(blank=True, default=(), related_name='image_liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, default=(), related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, default=(), related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='likes',
            field=models.ManyToManyField(blank=True, default=(), related_name='text_liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
